#  Q1): Write a program to create a 5 dimensional array with all zeros and ones


In [31]:
import numpy as np


In [12]:
np.array([[1,0,1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1,0,1]],ndmin=5)

array([[[[[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
          [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]]]])

# Q2): Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)



In [27]:
import numpy as np

np.array([[[0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1],[5,5,5,5,5,5,5,5,5,5]]])

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]])

# Q3): Write a program to create a 3x4 matrix filled with values from 10 to 21.



In [1]:
import numpy as np

In [3]:
array=np.arange(10,22).reshape(3,4)
array

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# Q4): Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [26]:
np.arange(0,10,1)
np.diag([0,1,2,3,4,5,6,7,8,9])


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

# Q5): Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [41]:
import numpy as np
a=np.arange(1,17).reshape(4,4)
a[:,[0,-1]]=a[:,[-1,0]]
a[:,[1,2]]=a[:,[2,1]]
a


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

# Q6): Write a program to reverse an array (the first element becomes the last).
# Given array:
# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [27]:
a=int(input())
b=int(input())
x=np.arange(a,b+1)
x[::-1]

12
27


array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

# Q7): Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100



In [39]:
import numpy as np
a=np.arange(1,101).reshape(10,10)
a=a[a%5==0]
a=a[a>30]
a=a[a<80]
a


array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# Q8): Write a program to create a 2D array with 1 on the border and 0 inside.



In [2]:
arr1=np.ones((9,9),dtype=int)
arr1[1:8,1:8]=0
arr1



array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Q9): Write a program to create a checkerboard pattern .Don't use default array function Checkerboard pattern:                                                   
#  [[0 1 0 1 0 1 0 1]                                                      
#  [1 0 1 0 1 0 1 0]                                                      
#  [0 1 0 1 0 1 0 1]                                                      
#  [1 0 1 0 1 0 1 0]                                                      
#  [0 1 0 1 0 1 0 1]                                                      
#  [ 1 0 1 0 1 0 1 0]                                                      
#  [0 1 0 1 0 1 0 1]                                                      
#  [1 0 1 0 1 0 1 0]]


In [5]:
import numpy as np
arr1=np.zeros((8,8),dtype=int)
arr1[[0,0,0,0],[1,3,5,7]]=1
arr1[[1,1,1,1],[0,2,4,6]]=1
arr1[[2,2,2,2],[1,3,5,7]]=1
arr1[[3,3,3,3],[0,2,4,6]]=1
arr1[[4,4,4,4],[1,3,5,7]]=1
arr1[[5,5,5,5],[0,2,4,6]]=1
arr1[[6,6,6,6],[1,3,5,7]]=1
arr1[[7,7,7,7],[0,2,4,6]]=1
arr1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Q10): Write a program to find common values between two arrays.
# Expected Output:
# array1: [10 20 40 60]
# array2: [10, 30, 40,50]


In [1]:
import numpy as np
x=np.array([[1,2,3,4,5,6]])
y=np.array([[4,5,6,7,8,9]])
np.intersect1d(x,y)

array([4, 5, 6])

# Q11): Write a program to create an array 2d array and then reshape into 1d array


In [36]:
x=np.arange(1,21).reshape(4,5)
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Q12): Write a user defined function for creating a 1 or 2d array from scratch without using array functions



In [8]:
 def array_2d(x):
        n=int(input("enter the dimention: "))
        s=len(x)
        if n==1:
            print("array({})".format(x))
        elif n==2:
            print("array([",end="")
            print("[{}]".format(x[0]))
            for y in range(1,s-1):
                print("       [{}]".format(x[y]))
            for y in range(s-1,s):
                print("       [{}]".format(x[y],end=""))
                print("])")
l=[]
k=int(input("enter no of elements: "))
for i in range(k):
    a=input("enter the element: ")
    l.append(a)
print(l)
array_2d(l)

enter no of elements: 4
enter the element: 1,1,1,1
enter the element: 2,2,2,2
enter the element: 3,3,3,3
enter the element: 4,4,4,4
['1,1,1,1', '2,2,2,2', '3,3,3,3', '4,4,4,4']
enter the dimention: 2
array([[1,1,1,1]
       [2,2,2,2]
       [3,3,3,3]
       [4,4,4,4]
])
