In [2]:
import numpy as np

In [3]:
np.array(["1-total_bill","2-tip","3-sex","4-smoker","5-day","6-time","7-size"])


array(['1-total_bill', '2-tip', '3-sex', '4-smoker', '5-day', '6-time',
       '7-size'], dtype='<U12')

# extract data from csv file to numpy array

In [4]:
arr=np.genfromtxt(r"C:\Users\HARI KRISHNA\Downloads\tipsf.csv",delimiter=",",skip_header=1)
arr

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

# Q 1) : what is the total bill value?

In [5]:
total_bill=arr[:,1]
np.sum(total_bill)


4827.77

# Q 2) :  what is the total tip value?

In [6]:
total_tip=arr[:,2]
np.sum(total_tip)


731.5799999999999

# Q 3) : count how many sunday,saturday,thursday,fridays are there?

In [7]:
days=arr[:,5]
x=np.unique(days,return_counts=True)
x

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

# Q 4) : how many smokers are there? 

In [8]:
smoker=arr[:,4]
x=np.unique(smoker,return_counts=True)
x

(array([0., 1.]), array([151,  93], dtype=int64))

# Q 5) : what is the average tip given by female and male?

In [9]:
avg_male_tip=arr[arr[:,3]!=0]
np.mean(avg_male_tip[:,2])

3.0896178343949043

In [10]:
avg_female_tip=arr[arr[:,3]==0]
np.mean(avg_female_tip[:,2])

2.8334482758620685

# Q 6) : how much amount is spent has been spent by female?


In [11]:
female_bill=arr[arr[:,3]==0]
np.sum(female_bill[:,1])

1570.9499999999996

# Q 7) : what is the minimum and maximum tip given?

In [12]:
tip=arr[:,2]
np.min(tip)

1.0

In [13]:
np.max(tip)

10.0

# Q 8) : howmany males and females are going for dinner,and lunch?

In [26]:
lunch=arr[arr[:,6]==0]
male_lunch=lunch[lunch[:,3]==1]
female_lunch=lunch[lunch[:,3]==0]
print("total_male_lunch are:",len(male_lunch))
print("total_female_lunch are:",len(female_lunch))

total_male_lunch are: 124
total_female_lunch are: 52


In [27]:
dinner=arr[arr[:,6]==1]
male_dinner=dinner[dinner[:,3]==1]
female_dinner=dinner[dinner[:,3]==0]
print("total_male_dinner are:",len(male_dinner))
print("total_female_dinner are:",len(female_dinner))

total_male_dinner are: 33
total_female_dinner are: 35


# Q 9) : find out the average size?

In [14]:
size=arr[:,7]
np.mean(size)

2.569672131147541

# Q 10) : how many female smokers are there and male smokers are there? 

In [24]:
smokers=arr[arr[:,4]==1]
male_smokers=smokers[smokers[:,3]==1]
female_smokers=smokers[smokers[:,3]==0]
print("total_male_smokers are:",len(male_smokers))
print("total_female_smokers are:",len(female_smokers))


total_male_smokers are: 60
total_female_smokers are: 33


In [8]:
np.array(["1-Length","2-Diameter","3-Height","4-Weight","5-Shucked Weight","6-Viscera Weight","7-Shell Weight","8-Age"])

array(['1-Length', '2-Diameter', '3-Height', '4-Weight',
       '5-Shucked Weight', '6-Viscera Weight', '7-Shell Weight', '8-Age'],
      dtype='<U16')

# extract data from csv file to numpy array

In [68]:
arr=np.genfromtxt(r"C:\Users\HARI KRISHNA\Downloads\train_extended.csv",delimiter=",",skip_header=1)
arr

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

# Q 1) : what is the minimum and maximum length?

In [15]:
x=arr[:,0]
x

array([1.575 , 1.2375, 1.45  , ..., 1.125 , 1.625 , 1.5875])

In [16]:
np.max(x)

7.58349125

In [17]:
np.min(x)

0.0

# Q 2) : what is the difference between minimum and maximum length ?

In [19]:
np.max(x)-np.min(x)

7.58349125

# Q 3) :find columnwise average 

In [23]:
def f(x):
    return np.mean(x)
average=np.apply_along_axis(f,1,arr)
average  

array([ 9.08330322,  7.82573462,  8.45955359, ...,  3.77732269,
        9.96966509, 10.24930997])

# Q 4) :findout all the ages whose height is greater than 0.4

In [29]:
x=arr[arr[:,2]>0.4]
x[:,7]

array([11., 14., 13., ..., 11., 11., 11.])

# Q 5) :what is the average height and weight of the persons whose age is 10?

In [65]:
age=arr[arr[:,7]==10]
avg=age[:,3:5]
def f(y):
    return np.mean(y)
average=np.apply_along_axis(f,0,avg)
average  

array([28.24330845, 12.50283908])

# Q 6) :what is the shell weight?

In [66]:
shell_weight=arr[:,6]
np.sum(shell_weight)

1326845.8295214002

# Q 7) :how many persons belongs belongs to each and every unique age?

In [48]:
age=arr[:,7]
np.unique(age,return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

# Q 8) :what is the difference between shucked weight and viscera weight?

In [51]:
shucked_weight=arr[:,4]
viscera_weight=arr[:,5]
difference=shucked_weight-viscera_weight
difference

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

# Q 9) :what is the average height of the person whose age is between 14 & 19?

In [59]:
x=arr[arr[:,7]>14] 
y=x[x[:,7]<19]
z=y[:,3]
np.mean(z)

32.11337167476735

# Q 10) :what is the average weight if we include shucker weight,viscera weight & shell weight?

In [64]:
avg=arr[:,3:7]
avg
def f(x):
    return np.mean(x)
average=np.apply_along_axis(f,0,avg)
average  

array([23.12343631,  9.98937025,  4.99318096,  6.63422915])

In [21]:
smokers=arr[arr[:,4]==1]
smokers



array([[ 56.  ,  38.01,   3.  ,   1.  ,   1.  ,   0.  ,   0.  ,   4.  ],
       [ 58.  ,  11.24,   1.76,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 60.  ,  20.29,   3.21,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 61.  ,  13.81,   2.  ,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 62.  ,  11.02,   1.98,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 63.  ,  18.29,   3.76,   1.  ,   1.  ,   0.  ,   0.  ,   4.  ],
       [ 67.  ,   3.07,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ],
       [ 69.  ,  15.01,   2.09,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 72.  ,  26.86,   3.14,   0.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 73.  ,  25.28,   5.  ,   0.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 76.  ,  17.92,   3.08,   1.  ,   1.  ,   0.  ,   0.  ,   2.  ],
       [ 80.  ,  19.44,   3.  ,   1.  ,   1.  ,   2.  ,   1.  ,   2.  ],
       [ 83.  ,  32.68,   5.  ,   1.  ,   1.  ,   2.  ,   1.  ,   2.  ],
       [ 90.  ,  28.97,   3.  ,   1.  ,   1.  ,   3